version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: Postgres-Agenda
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  apis:
    build: .
    container_name: Backend
    ports:
      - "${PYTHON_API_PORT}:${PYTHON_API_PORT}"
      - "${GO_API_PORT}:${GO_API_PORT}"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      DB_HOST: postgres
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  # =================================================================
  # Frontend
  # =================================================================
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: FrontEnd
    ports:
      - "7000:7000"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
