services:
  frontend:
    container_name: frontend
    depends_on:
      - backend-login
    build: ./frontend
    ports:
      - 7000:80
    networks:
      - agendapro
    restart: always

  backend-login:
    container_name: backend-login
    depends_on:
      - backend-app
    build: ./backend/golang
    environment:
      - JWT_KEY=${JWT_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - ${GO_API_PORT}:8181
    networks:
      - agendapro
    restart: always

  backend-app:
    container_name: backend-app
    depends_on:
      - db
    build: ./backend/python
    environment:
      - JWT_KEY=${JWT_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - ${PYTHON_API_PORT}:8585
    networks:
      - agendapro
    restart: always

  db:
    container_name: db-agendapro
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agendapro
    restart: always


volumes:
  postgres:

networks:
  agendapro:
