services:
  frontend:
    container_name: frontend
    depends_on:
      - backend-login
    build: ./frontend
    ports:
      - 7000:80
    networks:
      - agendapro
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /usr/share/nginx/html

  backend-login:
    container_name: backend-login
    depends_on:
      - backend-app
    build: ./backend/golang
    environment:
      - JWT_KEY=${JWT_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - ${GO_API_PORT}:8181
    networks:
      - agendapro
    develop:
      watch:
        - action: sync
          path: ./backend/golang
          target: /app
          ignore:
            - .env
        - action: rebuild
          path: go.sum

  backend-app:
    container_name: backend-app
    depends_on:
      - db
    build: ./backend/python
    environment:
      - JWT_KEY=${JWT_KEY}
      - POSTGRES_URL=${POSTGRES_URL}
    ports:
      - ${PYTHON_API_PORT}:8585
    networks:
      - agendapro
    develop:
      watch:
        - action: sync
          path: ./backend/python
          target: /python
          ignore:
            - __pycache__/
            - logs/
            - venv/
            - requirements.txt
        - action: rebuild
          path: ./init.sql

  db:
    container_name: db-agendapro
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - agendapro


volumes:
  postgres:

networks:
  agendapro:
